/**
 * ModelAdapter.ts
 * Core abstraction interface and implementations for AI model adapters.
 * Enables easy swapping and addition of different LLM providers.
 */

/**
 * Configuration object for recommendation generation
 */
export interface RecommendationConfig {
  temperature?: number;
  maxTokens?: number;
  topP?: number;
  [key: string]: unknown;
}

/**
 * Interface for AI model adapters.
 * All model adapters must implement this interface to ensure compatibility
 * with the SpontaneityEngine.
 */
export interface IModelAdapter {
  /**
   * Generates a recommendation based on the provided prompt and configuration.
   * 
   * @param prompt - The user input or prompt to generate recommendations from
   * @param config - Optional configuration object for the generation (temperature, maxTokens, etc.)
   * @returns Promise resolving to a JSON string containing the recommendation
   */
  generateRecommendation(prompt: string, config?: RecommendationConfig): Promise<string>;
}

/**
 * Adapter for Google's Gemini AI model.
 * Implements IModelAdapter to integrate with SpontaneityEngine.
 */
export class GeminiAdapter implements IModelAdapter {
  private apiKey: string;

  /**
   * Creates a new GeminiAdapter instance.
   * 
   * @param apiKey - The Gemini API key for authentication
   */
  constructor(apiKey: string) {
    if (!apiKey) {
      throw new Error('GeminiAdapter requires an API key');
    }
    this.apiKey = apiKey;
  }

  /**
   * Generates a recommendation using the Gemini API.
   * Currently returns a mock response for development.
   * 
   * @param prompt - The user input prompt
   * @param config - Optional configuration for generation
   * @returns Promise resolving to a JSON string with recommendation data
   */
  async generateRecommendation(
    prompt: string,
    config: RecommendationConfig = {}
  ): Promise<string> {
    try {
      // Simulate API call - replace with actual Gemini API integration
      // For now, returns mock JSON response
      const mockResponse = {
        model: 'gemini-pro',
        recommendation: `Gemini-generated recommendation for: "${prompt.substring(0, 50)}..."`,
        activities: [
          {
            name: 'Spontaneous Adventure',
            type: 'outdoor',
            duration: '2-3 hours',
            confidence: 0.85
          }
        ],
        reasoning: 'Generated by Gemini adapter (mock response)',
        config: config,
        timestamp: new Date().toISOString()
      };

      // Simulate network delay
      await new Promise(resolve => setTimeout(resolve, 100));

      return JSON.stringify(mockResponse);
    } catch (error) {
      const errorMessage = error instanceof Error ? error.message : 'Unknown error';
      throw new Error(`GeminiAdapter error: ${errorMessage}`);
    }
  }
}

/**
 * Adapter for OpenAI's GPT models.
 * Implements IModelAdapter to integrate with SpontaneityEngine.
 */
export class OpenAIAdapter implements IModelAdapter {
  private apiKey: string;

  /**
   * Creates a new OpenAIAdapter instance.
   * 
   * @param apiKey - The OpenAI API key for authentication
   */
  constructor(apiKey: string) {
    if (!apiKey) {
      throw new Error('OpenAIAdapter requires an API key');
    }
    this.apiKey = apiKey;
  }

  /**
   * Generates a recommendation using the OpenAI API.
   * Currently returns a mock response for development.
   * 
   * @param prompt - The user input prompt
   * @param config - Optional configuration for generation
   * @returns Promise resolving to a JSON string with recommendation data
   */
  async generateRecommendation(
    prompt: string,
    config: RecommendationConfig = {}
  ): Promise<string> {
    try {
      // Simulate API call - replace with actual OpenAI API integration
      // For now, returns mock JSON response
      const mockResponse = {
        model: 'gpt-4',
        recommendation: `OpenAI-generated recommendation for: "${prompt.substring(0, 50)}..."`,
        activities: [
          {
            name: 'Creative Experience',
            type: 'indoor',
            duration: '1-2 hours',
            confidence: 0.90
          }
        ],
        reasoning: 'Generated by OpenAI adapter (mock response)',
        config: config,
        timestamp: new Date().toISOString()
      };

      // Simulate network delay
      await new Promise(resolve => setTimeout(resolve, 100));

      return JSON.stringify(mockResponse);
    } catch (error) {
      const errorMessage = error instanceof Error ? error.message : 'Unknown error';
      throw new Error(`OpenAIAdapter error: ${errorMessage}`);
    }
  }
}

